-- Servicios, proyectos y clientes iniciales (los que hoy trae la web + 4 servicios nuevos).
--
-- Cómo usarlo: aplicar antes la migración 20261001200000_servicios_proyectos_clientes y luego pegar y
-- ejecutar esto en el SQL Editor de Supabase (o con psql). Es idempotente: si el servicio (slug) ya existe en
-- la marca no lo pisa, y proyectos/clientes con el mismo título/nombre no se duplican. Después se gestiona todo
-- desde Dashboard → Soluciones/Web.
--
-- Marca: toma la primera cuyo nombre contenga "fptecnologi".
-- Los 4 servicios nuevos (soporte técnico y postventa, redes y cableado, ciberseguridad y licenciamiento) son un
-- BORRADOR de texto: revisarlos y ajustarlos desde el dashboard antes de comunicarlos.
-- Proyectos y clientes son DE EJEMPLO (esEjemplo = true): se muestran en la web pero no se le pasan al asistente
-- virtual como casos reales. Reemplazarlos por los reales y desmarcar "ejemplo".

-- ============================== Servicios ==============================
WITH m AS (
  SELECT id FROM "Marca" WHERE nombre ILIKE '%fptecnologi%' ORDER BY "createdAt" LIMIT 1
)
INSERT INTO "Servicio"
  ("id","marcaId","nombre","descripcion","activo","slug","etiqueta","icono","imagenUrl","intro","incluye","beneficios","sectores","faqs","orden","updatedAt")
SELECT gen_random_uuid()::text, m.id, v.nombre, v.descripcion, true, v.slug, v.etiqueta, v.icono, v.imagen, v.intro, v.incluye, v.beneficios, v.sectores, v.faqs, v.orden, now()
FROM m,
(VALUES
  ('Seguridad ciudadana', 'seguridad-ciudadana', 'Somos expertos en', 'shield', '/images/solutions/seguridad.jpg', 'Cámaras, control de accesos y videovigilancia integrada para municipios, condominios y empresas.', 'Diseñamos e implementamos sistemas de videovigilancia y control de accesos para municipios, condominios y empresas: cámaras en los puntos críticos, grabación centralizada y monitoreo desde una central.', ARRAY['Estudio de puntos críticos y cobertura','Cámaras IP y de lectura de placas','Grabación centralizada (NVR / servidores)','Central de monitoreo con videowall','Control de accesos y alarmas','Enlaces de red y fibra para las cámaras']::text[], '[{"titulo":"Monitoreo 24/7","texto":"Una sola central para ver y gestionar todas las cámaras."},{"titulo":"Evidencia confiable","texto":"Grabaciones de alta calidad disponibles cuando las necesitas."},{"titulo":"Crece contigo","texto":"Suma cámaras y sedes sin rehacer la infraestructura."}]'::jsonb, ARRAY['Municipalidades','Condominios','Empresas','Almacenes y plantas']::text[], '[{"p":"¿Puedo ver las cámaras desde el celular?","r":"Sí, configuramos el acceso remoto seguro desde el celular o la computadora."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 1),
  ('Escuelas y universidades', 'escuelas-y-universidades', 'Soluciones para', 'academic', '/images/solutions/escuelas.jpg', 'Equipamiento y conectividad para aulas, laboratorios y campus, con soporte técnico dedicado.', 'Equipamos aulas, laboratorios y campus con la tecnología que necesita la educación de hoy: pantallas interactivas, laboratorios de cómputo y conectividad estable en todo el campus.', ARRAY['Pantallas interactivas para aulas','Laboratorios de cómputo completos','Wi-Fi para todo el campus','Cableado estructurado y racks','Servidores y almacenamiento académico','Capacitación a docentes']::text[], '[{"titulo":"Clases más dinámicas","texto":"Contenido interactivo que mejora la participación."},{"titulo":"Conectividad estable","texto":"Internet confiable en aulas, laboratorios y áreas comunes."},{"titulo":"Soporte dedicado","texto":"Acompañamiento técnico durante el año académico."}]'::jsonb, ARRAY['Colegios','Institutos','Universidades','Centros de capacitación']::text[], '[{"p":"¿Capacitan a los docentes en el uso de las pantallas?","r":"Sí, la implementación incluye capacitación para que el equipo docente las use desde el primer día."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 2),
  ('Servidores para empresas', 'servidores-para-empresas', 'Soluciones de', 'server', '/images/solutions/servidores.jpg', 'Servidores dimensionados a tu operación, con instalación, configuración y garantía oficial.', 'Dimensionamos, instalamos y configuramos servidores a la medida de tu operación: desde un servidor de archivos para una oficina hasta la infraestructura de virtualización de una empresa.', ARRAY['Dimensionamiento según tu carga de trabajo','Servidores torre y rack de marcas líderes','Virtualización y sistemas operativos','Almacenamiento y respaldo','Instalación en rack y energía (UPS)','Garantía oficial y soporte']::text[], '[{"titulo":"Rendimiento a medida","texto":"Ni de más ni de menos: lo que tu operación necesita."},{"titulo":"Continuidad","texto":"Componentes redundantes y respaldo para evitar caídas."},{"titulo":"Garantía oficial","texto":"Equipos originales con soporte del fabricante."}]'::jsonb, ARRAY['Pymes','Corporativos','Instituciones públicas','Salud']::text[], '[{"p":"¿Migran la información del servidor anterior?","r":"Sí, planificamos la migración para que tu operación no se detenga."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 3),
  ('Hoteles y restaurantes', 'hoteles-y-restaurantes', 'Soluciones para', 'building', '/images/solutions/hoteles.jpg', 'Redes, TV y sistemas de gestión pensados para la operación diaria del rubro hotelero y gastronómico.', 'Tecnología pensada para la operación diaria del rubro hotelero y gastronómico: Wi-Fi para huéspedes, TV, puntos de venta y la red que conecta todo.', ARRAY['Wi-Fi para huéspedes y personal','Sistemas de TV para habitaciones','Equipos para punto de venta','Cámaras de seguridad','Cableado y red de datos','Soporte técnico local']::text[], '[{"titulo":"Mejor experiencia","texto":"Huéspedes y clientes conectados sin interrupciones."},{"titulo":"Operación ágil","texto":"Caja, cocina y recepción trabajando en la misma red."},{"titulo":"Un solo proveedor","texto":"Equipos, instalación y soporte con el mismo equipo."}]'::jsonb, ARRAY['Hoteles','Hostales','Restaurantes','Cafeterías']::text[], '[{"p":"¿Separan la red de huéspedes de la red interna?","r":"Sí, configuramos redes independientes para proteger la información del negocio."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 4),
  ('Videoconferencia', 'videoconferencia', 'Soluciones de', 'video', '/images/solutions/videoconferencia.jpg', 'Salas de reunión equipadas con cámaras, audio e integración a las plataformas que ya usas.', 'Equipamos salas de reunión de todos los tamaños con cámaras, audio y pantallas que se integran con Teams, Zoom o Meet, para reuniones híbridas que se ven y se escuchan bien.', ARRAY['Diseño de la sala según su tamaño','Cámaras y barras de video','Micrófonos y audio de sala','Pantallas y soportes','Integración con Teams, Zoom o Meet','Capacitación a usuarios']::text[], '[{"titulo":"Reuniones sin fricción","texto":"Un clic para empezar, sin cables ni configuraciones."},{"titulo":"Audio y video claros","texto":"Todos se ven y se escuchan, estén en la sala o remotos."},{"titulo":"Compatibilidad","texto":"Funciona con las plataformas que tu equipo ya usa."}]'::jsonb, ARRAY['Corporativos','Educación','Sector público','Salud']::text[], '[{"p":"¿Funciona con Microsoft Teams y Zoom?","r":"Sí, trabajamos con equipos certificados para las principales plataformas."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 5),
  ('Data centers', 'data-centers', 'Implementamos', 'database', '/images/solutions/data-centers.jpg', 'Diseño e implementación de data centers, desde el rack hasta el cableado estructurado.', 'Diseñamos e implementamos data centers y cuartos de comunicaciones, desde el rack y la energía hasta el cableado estructurado y la climatización.', ARRAY['Diseño del cuarto de datos','Racks, gabinetes y ordenamiento','Cableado estructurado certificado','Energía redundante (UPS)','Climatización de precisión','Monitoreo y documentación']::text[], '[{"titulo":"Infraestructura ordenada","texto":"Cableado y equipos documentados, fáciles de mantener."},{"titulo":"Alta disponibilidad","texto":"Energía y climatización pensadas para no detenerse."},{"titulo":"Escalable","texto":"Espacio y capacidad para crecer sin rehacer todo."}]'::jsonb, ARRAY['Corporativos','Instituciones públicas','Educación','Industria']::text[], '[{"p":"¿Entregan la certificación del cableado?","r":"Sí, el cableado estructurado se entrega certificado y documentado."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 6),
  ('Datos empresariales', 'datos-empresariales', 'Gestión y respaldo de', 'cloud-upload', '/images/solutions/datos-empresariales.jpg', 'Respaldo, almacenamiento y políticas de recuperación para que la información de tu empresa esté segura.', 'Protegemos la información de tu empresa con soluciones de respaldo, almacenamiento y recuperación, para que un error, una falla o un ataque no detengan tu operación.', ARRAY['Diagnóstico de la información crítica','Almacenamiento en red (NAS / SAN)','Copias de respaldo automáticas','Respaldo fuera de sitio o en la nube','Plan de recuperación ante desastres','Pruebas de restauración']::text[], '[{"titulo":"Información segura","texto":"Copias automáticas y protegidas de tus datos."},{"titulo":"Recuperación rápida","texto":"Un plan probado para volver a operar cuanto antes."},{"titulo":"Tranquilidad","texto":"Tu equipo se enfoca en el negocio, no en los respaldos."}]'::jsonb, ARRAY['Pymes','Corporativos','Salud','Estudios profesionales']::text[], '[{"p":"¿Cada cuánto se hacen los respaldos?","r":"Definimos la frecuencia contigo según qué tan crítica es cada información."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 7),
  ('Soluciones cloud', 'soluciones-cloud', 'Soluciones de', 'cloud', '/images/solutions/cloud.jpg', 'Migración e infraestructura en la nube, a medida del tamaño y presupuesto de tu operación.', 'Llevamos tu infraestructura a la nube de forma ordenada: evaluamos qué conviene migrar, lo migramos sin detener tu operación y te ayudamos a controlar los costos.', ARRAY['Evaluación de lo que conviene migrar','Diseño de la arquitectura en la nube','Migración de servidores y datos','Correo y colaboración en la nube','Seguridad y accesos','Monitoreo y optimización de costos']::text[], '[{"titulo":"Flexibilidad","texto":"Crece o reduce recursos según tu operación."},{"titulo":"Acceso desde donde estés","texto":"Tu equipo trabaja desde la oficina o de forma remota."},{"titulo":"Costos claros","texto":"Pagas lo que usas, con acompañamiento para optimizarlo."}]'::jsonb, ARRAY['Pymes','Corporativos','Educación','Startups']::text[], '[{"p":"¿Se detiene mi operación durante la migración?","r":"Planificamos la migración por etapas para evitar interrupciones."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 8),
  ('Soporte técnico y postventa', 'soporte-tecnico-y-postventa', 'Servicio de', 'wrench', '/images/solutions/soporte-tecnico.jpg', 'Mantenimiento, soporte y gestión de garantías para los equipos de tu empresa, con técnicos locales.', 'Mantenemos operativos los equipos de tu empresa: atendemos incidencias, hacemos mantenimiento preventivo y correctivo y gestionamos la garantía oficial con cada marca, para que tu equipo no pare de trabajar.', ARRAY['Mesa de ayuda y atención de incidencias','Mantenimiento preventivo y correctivo','Gestión de garantía oficial con cada marca','Instalación y configuración de equipos','Inventario y diagnóstico de equipos','Contratos de soporte a medida']::text[], '[{"titulo":"Menos paradas","texto":"Atención rápida para que tu operación no se detenga."},{"titulo":"Un solo contacto","texto":"Un equipo que coordina contigo y con las marcas."},{"titulo":"Garantía gestionada","texto":"Nos encargamos del trámite de garantía de tus equipos."}]'::jsonb, ARRAY['Pymes','Corporativos','Instituciones públicas','Educación']::text[], '[{"p":"¿Atienden equipos que no compré con ustedes?","r":"Lo evaluamos caso por caso: escríbenos con la marca y el modelo y un asesor te confirma."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 9),
  ('Redes y cableado estructurado', 'redes-y-cableado-estructurado', 'Soluciones de', 'network', '/images/solutions/redes-cableado.jpg', 'Diseño e instalación de redes de datos y Wi-Fi, con cableado estructurado certificado y documentado.', 'Diseñamos e instalamos la red que conecta tu empresa: cableado estructurado, switches, Wi-Fi y enlaces entre sedes, con todo ordenado, rotulado y documentado.', ARRAY['Levantamiento y diseño de la red','Cableado estructurado certificado','Switches, routers y puntos de acceso Wi-Fi','Fibra óptica y enlaces entre sedes','Racks y ordenamiento','Documentación y rotulado']::text[], '[{"titulo":"Red estable","texto":"Conexión confiable en todas tus áreas."},{"titulo":"Crece contigo","texto":"Una base ordenada a la que puedes sumar puntos y sedes."},{"titulo":"Entrega documentada","texto":"Planos, rotulado y certificación del cableado."}]'::jsonb, ARRAY['Oficinas','Hoteles y restaurantes','Colegios y universidades','Almacenes y plantas']::text[], '[{"p":"¿Entregan la documentación de la red?","r":"Sí, entregamos el cableado certificado y documentado."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 10),
  ('Ciberseguridad', 'ciberseguridad', 'Protección y', 'lock', '/images/solutions/ciberseguridad.jpg', 'Protección de la red, los equipos y la información de tu empresa frente a amenazas y ataques.', 'Protegemos la red, los equipos y la información de tu empresa: evaluamos tus riesgos, implementamos firewall y protección de equipos y definimos políticas de acceso para que un ataque no detenga tu operación.', ARRAY['Diagnóstico de riesgos y vulnerabilidades','Firewall y protección de red','Protección de equipos y servidores','Seguridad de correo y navegación','Políticas de acceso y autenticación','Capacitación en buenas prácticas']::text[], '[{"titulo":"Menos riesgo","texto":"Cierra las puertas más comunes de ataque."},{"titulo":"Visibilidad","texto":"Sabes qué pasa en tu red y tus equipos."},{"titulo":"Tranquilidad","texto":"Tu información y tu operación mejor protegidas."}]'::jsonb, ARRAY['Pymes','Corporativos','Instituciones públicas','Salud']::text[], '[{"p":"¿Con qué marcas trabajan?","r":"Distribuimos soluciones de seguridad como Sophos y te recomendamos la que mejor se ajusta a tu caso."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 11),
  ('Licenciamiento de software', 'licenciamiento-de-software', 'Gestión de', 'key', '/images/solutions/licenciamiento.jpg', 'Asesoría y gestión de las licencias de software de tu empresa: compra, renovación y control.', 'Te ayudamos a tener el software de tu empresa en regla y sin gastar de más: revisamos qué licencias usas, te asesoramos qué necesitas y gestionamos la compra y las renovaciones.', ARRAY['Evaluación de las licencias que usas','Licencias de sistemas operativos y ofimática','Licencias de servidores y virtualización','Renovaciones y control de vencimientos','Asesoría para el uso legal del software','Migraciones y actualizaciones']::text[], '[{"titulo":"Software en regla","texto":"Licencias legales y respaldadas por el fabricante."},{"titulo":"Costos claros","texto":"Pagas por lo que realmente necesitas."},{"titulo":"Renovaciones al día","texto":"Control de vencimientos para que nada se interrumpa."}]'::jsonb, ARRAY['Pymes','Corporativos','Educación','Instituciones públicas']::text[], '[{"p":"¿Pueden ayudarme a ordenar las licencias que ya tengo?","r":"Sí, revisamos qué licencias tienes y cuáles necesitas."},{"p":"¿La visita técnica tiene costo?","r":"No. Visitamos tu sede, levantamos la información y te enviamos una propuesta sin compromiso."},{"p":"¿Qué pasa después de la instalación?","r":"Te acompañamos con soporte técnico local y gestionamos la garantía oficial de los equipos con cada marca."}]'::jsonb, 12)
) AS v(nombre, slug, etiqueta, icono, imagen, descripcion, intro, incluye, beneficios, sectores, faqs, orden)
ON CONFLICT ("marcaId","slug") DO NOTHING;

-- ============================== Proyectos ==============================
WITH m AS (
  SELECT id FROM "Marca" WHERE nombre ILIKE '%fptecnologi%' ORDER BY "createdAt" LIMIT 1
)
INSERT INTO "Proyecto"
  ("id","marcaId","titulo","departamento","imagenUrl","cliente","anio","descripcion","alcance","orden","activo","esEjemplo","updatedAt")
SELECT gen_random_uuid()::text, m.id, v.titulo, v.departamento, v.imagen, v.cliente, v.anio, v.descripcion, v.alcance, v.orden, true, true, now()
FROM m,
(VALUES
  ('Mejoramiento del servicio de seguridad ciudadana en el distrito de Jaén', 'cajamarca', '/images/solutions/seguridad.jpg', 'Municipalidad Provincial de Jaén', 2024, 'Centro de operaciones con videovigilancia integrada, cámaras en puntos críticos del distrito y monitoreo 24/7.', ARRAY['Videovigilancia','Centro de monitoreo','Fibra óptica']::text[], 1),
  ('Equipamiento de aulas y laboratorios de la Universidad Nacional de Jaén', 'cajamarca', '/images/solutions/escuelas.jpg', 'Universidad Nacional de Jaén', 2023, 'Laboratorios de cómputo y aulas equipadas con pantallas interactivas y red inalámbrica para todo el campus.', ARRAY['Pantallas','Laboratorios','Wi-Fi']::text[], 2),
  ('Implementación de data center para entidad financiera', 'lima', '/images/solutions/data-centers.jpg', 'Entidad financiera (confidencial)', 2024, 'Diseño e implementación de data center con racks, energía redundante, climatización y cableado estructurado.', ARRAY['Data center','Cableado estructurado','Energía']::text[], 3),
  ('Salas de videoconferencia para sede corporativa en San Isidro', 'lima', '/images/solutions/videoconferencia.jpg', 'Grupo corporativo', 2025, 'Doce salas de reunión con cámaras, audio profesional e integración con Teams y Zoom.', ARRAY['Videoconferencia','Audio','Integración']::text[], 4),
  ('Migración de infraestructura a la nube para empresa logística', 'lima', '/images/solutions/cloud.jpg', 'Operador logístico', 2025, 'Migración de servidores on-premise a la nube con alta disponibilidad y plan de respaldo.', ARRAY['Cloud','Migración','Respaldo']::text[], 5),
  ('Sistema de videovigilancia para la Municipalidad Provincial de Piura', 'piura', '/images/solutions/seguridad.jpg', 'Municipalidad Provincial de Piura', 2023, 'Red de cámaras en avenidas principales conectadas a la central de serenazgo.', ARRAY['Videovigilancia','Serenazgo']::text[], 6),
  ('Servidores y respaldo de datos para hospital regional', 'arequipa', '/images/solutions/servidores.jpg', 'Hospital regional', 2024, 'Servidores para la historia clínica electrónica con respaldo automático y recuperación ante desastres.', ARRAY['Servidores','Backup','Alta disponibilidad']::text[], 7),
  ('Conectividad y pantallas interactivas para colegios emblemáticos', 'arequipa', '/images/solutions/escuelas.jpg', 'Gerencia Regional de Educación', 2023, 'Conectividad de aulas y pantallas interactivas para clases digitales en colegios emblemáticos.', ARRAY['Conectividad','Pantallas interactivas']::text[], 8),
  ('Red y sistemas de gestión para cadena hotelera en Cusco', 'cusco', '/images/solutions/hoteles.jpg', 'Cadena hotelera', 2024, 'Red Wi-Fi para huéspedes, TV corporativa y sistemas de gestión para recepción y restaurante.', ARRAY['Redes','TV corporativa','Gestión']::text[], 9),
  ('Centro de operaciones de seguridad ciudadana en Trujillo', 'la-libertad', '/images/solutions/seguridad.jpg', 'Municipalidad Provincial de Trujillo', 2025, 'Centro de operaciones con videowall, puestos de monitoreo y cámaras en el centro histórico.', ARRAY['Videowall','Videovigilancia']::text[], 10),
  ('Respaldo y almacenamiento de datos para gobierno regional', 'junin', '/images/solutions/datos-empresariales.jpg', 'Gobierno Regional de Junín', 2024, 'Almacenamiento centralizado y políticas de respaldo para la información de las sedes regionales.', ARRAY['Almacenamiento','Backup']::text[], 11),
  ('Videoconferencia para sedes descentralizadas en Chiclayo', 'lambayeque', '/images/solutions/videoconferencia.jpg', 'Entidad pública', 2023, 'Salas de videoconferencia para conectar la sede central con oficinas descentralizadas.', ARRAY['Videoconferencia','Redes']::text[], 12)
) AS v(titulo, departamento, imagen, cliente, anio, descripcion, alcance, orden)
WHERE NOT EXISTS (SELECT 1 FROM "Proyecto" x WHERE x."marcaId" = m.id AND x.titulo = v.titulo);

-- ============================== Clientes ==============================
WITH m AS (
  SELECT id FROM "Marca" WHERE nombre ILIKE '%fptecnologi%' ORDER BY "createdAt" LIMIT 1
)
INSERT INTO "Cliente"
  ("id","marcaId","nombre","sigla","logoUrl","sector","orden","activo","esEjemplo","updatedAt")
SELECT gen_random_uuid()::text, m.id, v.nombre, v.sigla, v.logo, v.sector, v.orden, true, true, now()
FROM m,
(VALUES
  ('Municipalidad Provincial', 'MP', NULL, 'gobierno', 1),
  ('Municipalidad Distrital', 'MD', NULL, 'gobierno', 2),
  ('Gobierno Regional', 'GR', NULL, 'gobierno', 3),
  ('Hospital Regional', 'HR', NULL, 'gobierno', 4),
  ('Serenazgo Municipal', 'SM', NULL, 'gobierno', 5),
  ('Entidad Pública', 'EP', NULL, 'gobierno', 6),
  ('Dirección Regional', 'DR', NULL, 'gobierno', 7),
  ('Centro de Salud', 'CS', NULL, 'gobierno', 8),
  ('Universidad Nacional', 'UN', NULL, 'educacion', 9),
  ('Universidad Privada', 'UP', NULL, 'educacion', 10),
  ('Instituto Tecnológico', 'IT', NULL, 'educacion', 11),
  ('Colegio Emblemático', 'CE', NULL, 'educacion', 12),
  ('Escuela Técnica', 'ET', NULL, 'educacion', 13),
  ('Colegio Privado', 'CP', NULL, 'educacion', 14),
  ('Operador Portuario', 'OP', NULL, 'privado', 15),
  ('Empresa Minera', 'EM', NULL, 'privado', 16),
  ('Operador Logístico', 'OL', NULL, 'privado', 17),
  ('Cadena de Tiendas', 'CT', NULL, 'privado', 18),
  ('Cadena Hotelera', 'CH', NULL, 'privado', 19),
  ('Entidad Financiera', 'EF', NULL, 'privado', 20)
) AS v(nombre, sigla, logo, sector, orden)
WHERE NOT EXISTS (SELECT 1 FROM "Cliente" x WHERE x."marcaId" = m.id AND x.nombre = v.nombre);
