/** Departamentos del Perú (mismos ids que usa el mapa de proyectos de la web pública). */
export const DEPARTAMENTOS: { id: string; name: string }[] = [
  { id: 'amazonas', name: 'Amazonas' },
  { id: 'ancash', name: 'Ancash' },
  { id: 'apurimac', name: 'Apurimac' },
  { id: 'arequipa', name: 'Arequipa' },
  { id: 'ayacucho', name: 'Ayacucho' },
  { id: 'cajamarca', name: 'Cajamarca' },
  { id: 'callao', name: 'Callao' },
  { id: 'cusco', name: 'Cusco' },
  { id: 'huancavelica', name: 'Huancavelica' },
  { id: 'huanuco', name: 'Huanuco' },
  { id: 'ica', name: 'Ica' },
  { id: 'junin', name: 'Junin' },
  { id: 'la-libertad', name: 'La Libertad' },
  { id: 'lambayeque', name: 'Lambayeque' },
  { id: 'lima', name: 'Lima' },
  { id: 'loreto', name: 'Loreto' },
  { id: 'madre-de-dios', name: 'Madre De Dios' },
  { id: 'moquegua', name: 'Moquegua' },
  { id: 'pasco', name: 'Pasco' },
  { id: 'piura', name: 'Piura' },
  { id: 'puno', name: 'Puno' },
  { id: 'san-martin', name: 'San Martin' },
  { id: 'tacna', name: 'Tacna' },
  { id: 'tumbes', name: 'Tumbes' },
  { id: 'ucayali', name: 'Ucayali' },
];
